# Generated by Django 5.0.2 on 2024-02-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_email_valid_profile_is_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_valid',
            new_name='is_approved',
        ),
    ]
