# Generated by Django 4.0.4 on 2024-03-20 12:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_token_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('ip', models.GenericIPAddressField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
