# Generated by Django 4.0.4 on 2024-03-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
