# Generated by Django 5.1.3 on 2025-01-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_certification_credential_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='certification',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='education',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
