# Generated by Django 5.1.3 on 2025-08-10 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_about'),
        ('resume', '0003_alter_certification_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['position', '-end_date', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['position', '-is_current', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['position', 'title']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['position', 'name']},
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer', models.CharField(blank=True, max_length=100, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('resumes', models.ManyToManyField(blank=True, related_name='awards', to='resume.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='accounts.profile')),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('resumes', models.ManyToManyField(blank=True, related_name='interests', to='resume.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='accounts.profile')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('proficiency', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('resumes', models.ManyToManyField(blank=True, related_name='languages', to='resume.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='accounts.profile')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('resumes', models.ManyToManyField(blank=True, related_name='references', to='resume.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='accounts.profile')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
    ]
