# Generated by Django 5.1.3 on 2025-08-11 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_certification_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['title']},
        ),
    ]
