# Generated by Django 5.1.3 on 2025-08-11 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
