# Generated by Django 5.1.3 on 2025-08-11 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_about'),
        ('resume', '0006_delete_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('resumes', models.ManyToManyField(blank=True, related_name='additional_infos', to='resume.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_infos', to='accounts.profile')),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
    ]
